# Generated by Django 5.1.7 on 2025-03-11 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_subscriptionsmodel"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="subscriptionsmodel",
            options={
                "verbose_name": "Подписчик",
                "verbose_name_plural": "Подписчики",
            },
        ),
        migrations.AlterModelOptions(
            name="usermodel",
            options={
                "ordering": ["-id"],
                "verbose_name": "Пользователь",
                "verbose_name_plural": "Пользователи",
            },
        ),
    ]
