# Generated by Django 5.1.7 on 2025-03-11 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0003_alter_recipeingredientmodel_amount_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="recipesmodel",
            options={
                "ordering": ["-id"],
                "verbose_name": "Рецепт",
                "verbose_name_plural": "Рецепты",
            },
        ),
    ]
